version: '3'
services:
  jobms:
    image: nigglenandu/jobappimage:latest
    container_name: JobMicroService
    ports:
      - "8082:8082"
    environment:
      - SPRING_APPLICATION_NAME=JobMicroService
      - SERVER_PORT=8082
      - SPRING_H2_CONSOLE_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:test
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_ZIPKIN_BASE_URL=http://zipkin:9411/
    networks:
      - mynetwork
    depends_on:
      - zipkin

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
